### ISSUE TITLE
[Feature]: Develop Contact Us Form for User Inquiries

### ISSUE THREAD

**Issue by SilverBeing** [hngprojects/hng_boilerplate_nextjs#140] opened 2024-07-17 17:14 UTC
### Description

Develop a Contact Us form that includes fields for user's name, email address, phone number  and message. Ensure the form integrates with backend API endpoints to handle form submissions, validate input data, and display appropriate feedback messages to the user.

### Acceptance Criteria

- [ ] Develop a form with fields for user's name, email address, phone number (optional), and message.
- [ ] Implement form validation to ensure required fields are filled and valid email format is entered.
- [ ] Integrate the form with backend API endpoints to handle form submissions.
- [ ] Display success or error messages based on API response.
- [ ] Ensure the form matches the provided design specifications and is responsive.
- [ ] Write unit tests to verify form validation, API integration, and responsiveness.

**Deadline: Friday 10am**

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=432-7567&m=dev
![image](https://github.com/user-attachments/assets/6fb284ff-eaa8-485f-b6df-54ee169d3b84)

**Comment by chumex412** [comment] 2024-07-18 00:54
This is just a duplicate of #143

**Comment by SilverBeing** [comment] 2024-07-18 10:19
@chumex412 #143 is dependent on this form to create the contact us page

**Comment by chumex412** [comment] 2024-07-18 10:45
Is it?
Because it has similar description and criteria to #143

**Comment by SilverBeing** [comment] 2024-07-18 11:02
@chumex412 in the description of #143 I clearly stated that it should integrate the already built form of another intern. Do I take it out

**Comment by chumex412** [comment] 2024-07-18 11:11
Could you remove this ticket, I don't see the point. What did the third person integrating both components do if an intern works on the form and another works on the content to the right?

It should be one whole ticket that one person or two people can work on. Structure the issue to indicate the blocking blocks if two people will work on it.

**Comment by SilverBeing** [comment] 2024-07-18 11:23
There is no issue for the content on the side. The person creating the contact page was supposed to create the content on the right but get the form component

**Comment by chumex412** [comment] 2024-07-18 11:37
Alright then

Give #143 a specific description based on what you just said and remove the redundancies. Point to this ticket from #143. Let the person working on #143 create that layout to the right and integrate the contact form. He/she should make sure the form works properly based on the test.

**Comment by SilverBeing** [comment] 2024-07-18 12:09
I have done that...Can this move to approved so I can link it to its parent

**Closed as completed** 2024-07-20 18:07 UTC
Labels: approved
